### ISSUE TITLE
`location` is a javascript reserve word

### ISSUE THREAD

**Issue by tomatohammado** [pnblake/dive-log-app#1]
https://github.com/pnblake/dive-log-app/blob/5005ed673df2ea44df0ddb70e8e5886795285211/models/index.js#L6

Thank god for syntax highlighting! I noticed a slightly different color style around the word "Location" and lo an behold it is on the list of [reserve words for javascript](https://www.w3schools.com/js/js_reserved.asp)

It's a little clunky sounding, by "LocationName" or something to that effect might be semantically close while getting around the naming conflict

**Comment by pnblake** [comment]
Fixed it, thanks!
